name: Build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Unit Tests
        run: go test ./src/...
      - name: Integration Tests
        run: go test -exec sudo ./tests/...

      - name: Set Build Variables
        run: |
          version=$(date '+%y%m%d-%H%M%S')
          echo version=$version >> $GITHUB_ENV       
          echo asset=fileintegrity-v$version >> $GITHUB_ENV
          echo ldflags="-s -w -X 'github.com/aicirt2012/fileintegrity.Version=$version'" >> $GITHUB_ENV
      
      - name: Build
        run: |
          env GOARCH=amd64 go build -ldflags "$ldflags" -o ./$asset/linux/fileintegrity ./src/cli/main.go
          env GOOS=windows GOARCH=amd64 go build -ldflags "$ldflags" -o ./$asset/windows/fileintegrity.exe ./src/cli/main.go
          env GOOS=darwin GOARCH=amd64 go build -ldflags "$ldflags" -o ./$asset/macos/fileintegrity ./src/cli/main.go
     
      - name: Upload Asset
        uses: actions/upload-artifact@v3
        env:
          asset: ${{ env.asset }}
        with:
          name: ${{ env.asset }}.zip
          path: ${{ env.asset }}/
          if-no-files-found: error